image: eclipse-temurin:21-jdk

stages:
  - build
  - test
  - package
  - deploy

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle" # Cache Gradle dependencies

cache:
  paths:
    - .gradle/wrapper/
    - .gradle/caches/

before_script:
  - chmod +x ./backend/gradlew # Ensure Gradle wrapper is executable

build-backend:
  stage: build
  script:
    - ./gradlew build --no-daemon
  artifacts:
    paths:
      - build/libs/

test-backend:
  stage: test
  script:
    - ./gradlew test --no-daemon

package-backend:
  stage: package
  script:
    - ./gradlew bootJar --no-daemon
  artifacts:
    paths:
      - build/libs/

