type: web
name: calbuco-feliz-backend
runtime: docker
repo: https://github.com/tu-usuario/CalbucoFeliz-Backend.git
region: oregon
plan: starter
buildCommand: ""
startCommand: ""
healthCheckPath: /actuator/health
env: production
envVars:
  - key: SPRING_PROFILES_ACTIVE
    value: production
  - key: DATABASE_URL
    sync: false
  - key: DATABASE_USERNAME  
    sync: false
  - key: DATABASE_PASSWORD
    sync: false
  - key: JWT_SECRET
    sync: false
  - key: JWT_EXPIRATION
    value: "86400000"
  - key: JWT_REFRESH_EXPIRATION
    value: "604800000"
  - key: JWT_ISSUER
    value: "CalbucoFeliz"
  - key: CLOUDINARY_CLOUD_NAME
    sync: false
  - key: CLOUDINARY_API_KEY
    sync: false
  - key: CLOUDINARY_API_SECRET
    sync: false
  - key: TWILIO_ACCOUNT_SID
    sync: false
  - key: TWILIO_AUTH_TOKEN
    sync: false
  - key: TWILIO_PHONE_NUMBER
    sync: false
